const categories = [
  {
    id: 1,
    title: 'Electricista',
    icon: require('../../assets/icons/cord.png'),
    color: '#CEE2DF',
    borderColor: '#C3DCD7',
  },
  {
    id: 2,
    title: 'Plomero',
    borderColor: '#BBD1CC',
    color: '#C6D8D5',
    icon: require('../../assets/icons/wrench.png'),
  },
  {
    id: 3,
    title: 'Gasista',
    borderColor: '#FE9966',
    color: '#FEA97F',
    icon: require('../../assets/icons/fire.png'),
  },
  {
    id: 4,
    title: 'Jardinero',
    borderColor: '#E89366',
    color: '#EBA580',
    icon: require('../../assets/icons/sprout.png'),
  },
  {
    id: 5,
    title: 'Cerrajero',
    borderColor: '#FDCA6A',
    color: '#FDD383',
    icon: require('../../assets/icons/key.png'),
  },
  {
    id: 6,
    title: 'Mas',
    borderColor: '#F5B968',
    color: '#F7C482',
    icon: require('../../assets/icons/mas.png'),
  },
  {
    id: 7,
    title: 'Pintor',
    borderColor: '#CEE2DF',
    color: '#C3DCD7',
    icon: require('../../assets/icons/cord.png'),
  },
  {
    id: 8,
    title: 'Refrigeración',
    borderColor: '#BBD1CC',
    color: '#C6D8D5',
    icon: require('../../assets/icons/cord.png'),
  },
  {
    id: 9,
    title: 'Mudanzas',
    borderColor: '#FE9966',
    color: '#FEA97F',
    icon: require('../../assets/icons/cord.png'),
  },
  {
    id: 10,
    title: 'Limpieza',
    borderColor: '#E89366',
    color: '#EBA580',
    icon: require('../../assets/icons/cord.png'),
  },
  {
    id: 11,
    title: 'Fotógrafo',
    borderColor: '#FDCA6A',
    color: '#FDD383',
    icon: require('../../assets/icons/cord.png'),
  },
  {
    id: 12,
    title: 'DJ',
    borderColor: '#F5B968',
    color: '#F7C482',
    icon: require('../../assets/icons/cord.png'),
  },
  {
    id: 13,
    title: 'Mecánico',
    borderColor: '#CEE2DF',
    color: '#C3DCD7',
    icon: require('../../assets/icons/cord.png'),
  },
  {
    id: 14,
    title: 'Peluquero',
    borderColor: '#BBD1CC',
    color: '#C6D8D5',
    icon: require('../../assets/icons/cord.png'),
  },
  {
    id: 15,
    title: 'Personal Trainer',
    borderColor: '#FE9966',
    color: '#FEA97F',
    icon: require('../../assets/icons/cord.png'),
  },
  {
    id: 16,
    title: 'Profesor de Música',
    borderColor: '#E89366',
    color: '#EBA580',
    icon: require('../../assets/icons/cord.png'),
  },
  {
    id: 17,
    title: 'Profesor de Canto',
    borderColor: '#FDCA6A',
    color: '#FDD383',
    icon: require('../../assets/icons/cord.png'),
  },
  {
    id: 18,
    title: 'Nutricionista',
    borderColor: '#F5B968',
    color: '#F7C482',
    icon: require('../../assets/icons/cord.png'),
  },
  {
    id: 19,
    title: 'Veterinario',
    borderColor: '#CEE2DF',
    color: '#C3DCD7',
    icon: require('../../assets/icons/cord.png'),
  },
  {
    id: 20,
    title: 'Manicura',
    borderColor: '#BBD1CC',
    color: '#C6D8D5',
    icon: require('../../assets/icons/cord.png'),
  },
  {
    id: 21,
    title: 'Pedicura',
    borderColor: '#FE9966',
    color: '#FEA97F',
    icon: require('../../assets/icons/cord.png'),
  },
  {
    id: 22,
    title: 'Clases Particulares',
    borderColor: '#E89366',
    color: '#EBA580',
    icon: require('../../assets/icons/cord.png'),
  },
  {
    id: 23,
    title: 'Cadetería',
    borderColor: '#FDCA6A',
    color: '#FDD383',
    icon: require('../../assets/icons/cord.png'),
  },
  {
    id: 24,
    title: 'Abogados',
    borderColor: '#F5B968',
    color: '#F7C482',
    icon: require('../../assets/icons/cord.png'),
  },
  {
    id: 25,
    title: 'Contador',
    borderColor: '#CEE2DF',
    color: '#C3DCD7',
    icon: require('../../assets/icons/cord.png'),
  },
  {
    id: 26,
    title: 'Diseñador',
    borderColor: '#BBD1CC',
    color: '#C6D8D5',
    icon: require('../../assets/icons/cord.png'),
  },
  {
    id: 27,
    title: 'Programador',
    borderColor: '#FE9966',
    color: '#FEA97F',
    icon: require('../../assets/icons/cord.png'),
  },
];

export default categories;
