export const users = [
  {
    nombre: 'Juan',
    apellido: 'Gómez',
    calificacion: 4.5,
    descripcion: 'Electricista con experiencia en instalaciones residenciales.',
    profesiones: ['Electricista'],
    verificado: true,
    imagen: require('../../assets/photo.png'),
  },
  {
    nombre: 'María',
    apellido: 'Martínez',
    calificacion: 3.8,
    descripcion: 'Gasista matriculado, especialista en reparaciones de gas.',
    profesiones: ['Gasista'],
    verificado: false,
    imagen: require('../../assets/photo.png'),
  },
  {
    nombre: 'Carlos',
    apellido: 'Fernández',
    calificacion: 4.2,
    descripcion: 'Plomero con habilidades en fontanería y reparaciones.',
    profesiones: ['Plomero'],
    verificado: true,
    imagen: require('../../assets/photo.png'),
  },
  {
    nombre: 'Ana',
    apellido: 'López',
    calificacion: 4.9,
    descripcion:
      'Técnica en climatización, experta en sistemas de aire acondicionado.',
    profesiones: ['Climatización'],
    verificado: true,
    imagen: require('../../assets/photo.png'),
  },
  {
    nombre: 'Pablo',
    apellido: 'García',
    calificacion: 3.5,
    descripcion: 'Experto en pintura y remodelación de interiores.',
    profesiones: ['Pintor'],
    verificado: false,
    imagen: require('../../assets/photo.png'),
  },
  {
    nombre: 'Laura',
    apellido: 'Rodríguez',
    calificacion: 4.0,
    descripcion:
      'Cerrajera con amplia experiencia en aperturas y reparaciones.',
    profesiones: ['Cerrajera'],
    verificado: true,
    imagen: require('../../assets/photo.png'),
  },
  {
    nombre: 'Martín',
    apellido: 'Díaz',
    calificacion: 4.7,
    descripcion: 'Especialista en jardinería y paisajismo.',
    profesiones: ['Jardinero'],
    verificado: false,
    imagen: require('../../assets/photo.png'),
  },
  {
    nombre: 'Sofía',
    apellido: 'Vega',
    calificacion: 3.2,
    descripcion: 'Carpintera con habilidades en muebles a medida.',
    profesiones: ['Carpintera'],
    verificado: true,
    imagen: require('../../assets/photo.png'),
  },
  {
    nombre: 'Diego',
    apellido: 'Hernández',
    calificacion: 4.4,
    descripcion: 'Experto en reparación de electrodomésticos.',
    profesiones: ['Reparación de Electrodomésticos'],
    verificado: true,
    imagen: require('../../assets/photo.png'),
  },
  {
    nombre: 'Elena',
    apellido: 'Suárez',
    calificacion: 3.9,
    descripcion: 'Diseñadora de interiores con enfoque en espacios modernos.',
    profesiones: ['Diseñadora de Interiores'],
    verificado: false,
    imagen: require('../../assets/photo.png'),
  },
];
